#!/bin/bash
#
#This script is run at the end of a Y1 summer lab.
#It pushes students' code to their GitHub repositories.
#
#(startlab should be run first, of course.)
#
#T. Golfinopoulos 26 June 2017
#Modified 29 May 2018
#Last modified 5 May 2019

source ~/.working_dir.sh

echo "???????????????????????????????????"
echo "Did you save _all_ your work in idle3 first?"
echo "If not, do it and run endlab again."
echo "???????????????????????????????????"
saved_flag=$(zenity --question --text="Did you save _all_ your work first from idle in $(pwd)?" --width=400 --ok-label="Yes" --cancel-label="No"; echo $? 2> /dev/null)

if [ $saved_flag=1 ]
then
    zenity --info --text="First, save all your work in $(pwd); then, run endlab again." 2> /dev/null #Suppress warning message
    return #Exit shell for user to re-run script
fi
#echo "Note: you can run endlab as many times as you want."

#Record which computer the student was working on
hostname > computer_name.txt

git add --all

username=$(git config --global user.name)

git commit -m "Stopping here"
git pull

#
zenity --info --text="Your username is\n$username\nYour password is\nmeetyear21\nEnter these in the terminal. When you type your password, you won't see text. That's okay." --width=400 2> /dev/null

echo "----------------------------------------"
echo "You'll be asked to enter your GitHub username and password"
echo "Your username is"
echo "$username"
echo "Your password is:"
echo "meetyear21"
echo "----------------------------------------"
echo "When you type your password, you won't see anything on the screen"
echo "That's okay - it protects your secrets!"
echo "If you make a mistake, try another time by running endlab again"
echo "----------------------------------------"
echo "????????????????????????????????????????????"
echo "Did you save _all_ your work in idle3 first?"
echo "If not, do it and run endlab again."
echo "????????????????????????????????????????????"
git push -u origin master

echo "----------------------------------------"
echo "Bye bye!"
